### ISSUE TITLE
Fetching all PRs in wpt-import-stats.py is slow

### ISSUE THREAD

**Issue by foolip** [foolip/ecosystem-infra-stats#2]
This step takes about a second per page and there are now 62 pages before "Reached cutoff point. Stop fetching more PRs."

It's likely that https://developer.github.com/v4/ could provide the same information in fewer requests, and @mattl has successfully used the API for something. (Don't remember what.)

@Hexcles FYI

**Comment by Hexcles** [comment]
Wow the number of PRs has been increasing super-linearly.

The short-term solution is to move the cut-off date later, which I'll do once I gather all the Q4 metrics I need.

**Comment by foolip** [comment]
@Hexcles, I guess we can close this now? (Reminded by https://github.com/foolip/ecosystem-infra-stats/pull/8)
