### ISSUE TITLE
PR merge_commit_sha field does not always point to the commit that closed the PR

### ISSUE THREAD

**Issue by foolip** [foolip/ecosystem-infra-stats#3]
Running wpt-import-stats.py today there are 1408 PRs, and 38 cases like this:
```
[224/1408] PR: https://github.com/w3c/web-platform-tests/pull/8876
fatal: git cat-file: could not get object info
Merge commit e8ce9b73438a41de9527f342c36ff505a328c9bb does not exist. SKIPPING!
```

The PRs pointed to are:
* https://github.com/w3c/web-platform-tests/pull/8876
* https://github.com/w3c/web-platform-tests/pull/8868
* https://github.com/w3c/web-platform-tests/pull/7843
* https://github.com/w3c/web-platform-tests/pull/7842
* https://github.com/w3c/web-platform-tests/pull/7841
* https://github.com/w3c/web-platform-tests/pull/7834
* https://github.com/w3c/web-platform-tests/pull/7831
* https://github.com/w3c/web-platform-tests/pull/7830
* https://github.com/w3c/web-platform-tests/pull/7829
* https://github.com/w3c/web-platform-tests/pull/7814
* https://github.com/w3c/web-platform-tests/pull/7742
* https://github.com/w3c/web-platform-tests/pull/7740
* https://github.com/w3c/web-platform-tests/pull/7739
* https://github.com/w3c/web-platform-tests/pull/7737
* https://github.com/w3c/web-platform-tests/pull/7736
* https://github.com/w3c/web-platform-tests/pull/7735
* https://github.com/w3c/web-platform-tests/pull/7732
* https://github.com/w3c/web-platform-tests/pull/7731
* https://github.com/w3c/web-platform-tests/pull/7730
* https://github.com/w3c/web-platform-tests/pull/7729
* https://github.com/w3c/web-platform-tests/pull/7724
* https://github.com/w3c/web-platform-tests/pull/7721
* https://github.com/w3c/web-platform-tests/pull/7720
* https://github.com/w3c/web-platform-tests/pull/7717
* https://github.com/w3c/web-platform-tests/pull/7716
* https://github.com/w3c/web-platform-tests/pull/7712
* https://github.com/w3c/web-platform-tests/pull/7710
* https://github.com/w3c/web-platform-tests/pull/7708
* https://github.com/w3c/web-platform-tests/pull/7707
* https://github.com/w3c/web-platform-tests/pull/7705
* https://github.com/w3c/web-platform-tests/pull/7702
* https://github.com/w3c/web-platform-tests/pull/7700
* https://github.com/w3c/web-platform-tests/pull/7402
* https://github.com/w3c/web-platform-tests/pull/7390
* https://github.com/w3c/web-platform-tests/pull/7111
* https://github.com/w3c/web-platform-tests/pull/7092
* https://github.com/w3c/web-platform-tests/pull/6823
* https://github.com/w3c/web-platform-tests/pull/6689

All that I've checked are Gecko or Servo exports, but presumably this could happen in other ways too.

Apparently this field is a common source of confusion:
https://developer.github.com/changes/2013-04-25-deprecating-merge-commit-sha/
https://developer.github.com/v3/pulls/#get-a-single-pull-request

This bit may be the problem: "If the pull request was rebased, the attribute represents the commit that the base branch was updated to."

@Hexcles FYI

**Comment by foolip** [comment]
It's not clear to me if there are also cases where the field point to an existing commit but is still somehow wrong. 8875 and 8877 looks correct, so at least it's not the case that PRs on either side of a problematic PR are also wrong. (But should look at merge order to be sure.)

**Comment by rakuco** [comment]
It's curious that in the case of 8876 the commit doesn't exist in a checkout, but can be viewed on GitHub: https://github.com/w3c/web-platform-tests/commit/e8ce9b73438a41de9527f342c36ff505a328c9bb

What if you stop relying on `merge_commit_sha` altogether and resort to doing some manual git black magic (e.g. get the first line of `git rev-list --reverse --ancestry-path --merges <commit>..master`)?

**Comment by foolip** [comment]
@rakuco, the trouble there I think would be getting `<commit>`. In the case where something has been rebased and/or squashed, the final commit doesn't appear anywhere previously. Ideas?

**Comment by Hexcles** [comment]
Perhaps I don't understand the docs correctly.

There are three cases (three different meanings) for this field after a PR is merged, all of which are (I think) what I want, which is why I thought this field was awesome (unifying the three different merge approaches in a sensible way)...

It's even more bizarre to me that a commit can be found on GitHub but not in a clone. I've only seen this before in stale, dangling commits that are supposed to be GC'ed eventually, but these commits in question supposedly go into the master branch, don't they?

**Comment by Hexcles** [comment]
Hypothesis: the previous gen of the Gecko exporter probably merges export PRs locally and then directly pushes to origin/master, which confuses GitHub's API / database. As a result, `merge_commit_sha` isn't updated and is still the **test** merge commit, despite that the PR has been merged.

If that's the case, we don't need to be concerned, because their new [wpt-sync](https://github.com/mozilla/wpt-sync) uses GitHub API to merge PRs properly. There will be few more examples of this in the future (when someone pushes a merge commit to master directly).

**Comment by foolip** [comment]
Since the original comment, there's been one more: https://github.com/w3c/web-platform-tests/pull/9014

**Comment by foolip** [comment]
Here's the script, written to find some missing tags, where I happened to notice:
```bash
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

curl "https://raw.githubusercontent.com/foolip/ecosystem-infra-stats/gh-pages/wpt-prs.csv" \
    | tail -n +2 | tr , ' ' | sort -k3 -r | while read pr sha date _; do
        tagname="merge_pr_$pr"
        tagsha="$(git rev-parse --revs-only $tagname 2> /dev/null)"  || :
        if [[ "$tagsha"  != "$sha" ]]; then
            echo "$tagname commit expected $sha got $tagsha"
        fi
    done
```

**Comment by foolip** [comment]
Not a drop-in replacement, as the 'author' and 'chromium_commit' fields rely on GitHub users and labels currently.
